# Generated by Django 3.0.8 on 2020-11-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255, unique=True)),
                ('player_1_name', models.CharField(max_length=30, verbose_name='Name of Player 1')),
                ('player_2_name', models.CharField(max_length=30, verbose_name='Name of Player 2')),
                ('player_3_name', models.CharField(max_length=30, verbose_name='Name of Player 3')),
                ('player_4_name', models.CharField(max_length=30, verbose_name='Name of Player 4')),
                ('player_5_name', models.CharField(max_length=30, verbose_name='Name of Player 5')),
                ('player_6_name', models.CharField(max_length=30, verbose_name='Name of Player 6')),
                ('player_7_name', models.CharField(max_length=30, verbose_name='Name of Player 7')),
                ('player_8_name', models.CharField(max_length=30, verbose_name='Name of Player 8')),
                ('player_9_name', models.CharField(max_length=30, verbose_name='Name of Player 9')),
                ('player_10_name', models.CharField(max_length=30, verbose_name='Name of Player 10')),
                ('player_11_name', models.CharField(max_length=30, verbose_name='Name of Player 11')),
            ],
        ),
    ]
